### PR TITLE
Dockers images to build android sample app

### PR DESCRIPTION
**Pull request by mgolokhov**
Connected tickets:

- Build a base gradle alpine image https://github.com/qaprosoft/jenkins-slave/issues/9
- Build an android alpine image https://github.com/qaprosoft/jenkins-slave/issues/10

To test run `sh` script:

```
#!/bin/bash
set -xe
docker build -t qaprosoft:gradle-alpine -f Dockerfile-gradle-alpine .
docker build -t qaprosoft:android-base-alpine -f Dockerfile-android-base-alpine .
docker build -t qaprosoft:android28-alpine -f Dockerfile-android28-alpine .
git clone https://github.com/qaprosoft/qps-sample-android.git
cd qps-sample-android
# android 28 mirrors version from the sample project
docker run -it --rm -v $PWD:/app qaprosoft:android28-alpine bash -c "gradle --no-daemon -b /app/build.gradle assembleDebug"
```

### CODE REVIEW

**Comment by vdelendik** [comment]
1. why do we need all these shell scripts? that's part of the sample android repo and could be removed from current repo
2. Let's put Jenkinsfile to the root and rename it to
Jenkinsfile-alpine-gradle

**Comment by mgolokhov** [comment]
It's a preliminary (intermediate step) solution. So shell scripts are just helpers to test.
Still, it may be a bad idea to leak information about a build system (gradle) in Jenkins.
For example, some big players use Bazel to build applications.
Jinkinsfile can be agnostic to a specific build system by expecting some shell script inside an application project (we can put it as future enhancement).

**Comment by mgolokhov** [comment]
A comparison to other base images:
Screenshot 2020-03-21 at 00 00 21

**Comment by vdelendik** [comment]
closing as out-of-dated

**Pull request closed without merging**
